language: python
python:
  - "3.2"
install:
  - pip install -r requirements.txt --use-mirrors
  - sudo apt-get install libcairo2-dev python3.2-dev python-scipy python-cairo libpango1.0-0
script:
  - make clean
  - make tests