language: python
python:
  - "2.7"
  - "3.2"
install:
  - pip install -r requirements.txt --use-mirrors
  - sudo apt-get install libcairo2-dev python3.2-dev python-scipy
script:
  - make clean
  - make tests
