sudo: required
dist: trusty
language: python
install:
  - sudo apt-get install libcairo2-dev python3-dev python-scipy python-cairo libpango1.0-0 libpixman-1-0 libcairomm-1.0-1 python-gi-cairo libpangomm-1.4-1 python-gtk2 python-numpy libpangocairo-1.0-0 libcairo2
  - pip install -r requirements.txt
script:
  - make clean
  - make install
  - make tests
